**PYTHON DAY1**

In [1]:
print("HELLO")

HELLO


In [8]:
name='hari'
age=23
cgpa=9.0
hobby = 'coding'
print('name:',name)
print('age:',age)
print('cgpa:',cgpa)
print('hobby:',hobby)

name: hari
age: 23
cgpa: 9.0
hobby: coding


In [9]:
cgpa=cgpa+0.07
print('cgpa:',cgpa)

cgpa: 9.07


lets try and print the student information in a more meaninful manner


In [11]:
print(f'the student name is {name} and they are {age} years old.')

the student name is hari and they are 23 years old.


lets calculate hari age in 15yr

In [12]:
age=age+15
print(f'the student name is {name} and they are {age} years old in 15yrs.')

the student name is hari and they are 38 years old in 15yrs.


In [ ]:
LIST AND OTHER TYPES OF DATA STRUCTURES

In [32]:
lst1=['hari',23,9.1,'true']
print(lst1)
print(lst1[2])
print(lst1[-1])
lst1[2:]
lst1[:2]

['hari', 23, 9.1, 'true']
9.1
true


['hari', 23]

In [23]:
lst1.append('hyderabad')
# print(lst1[-1)

In [27]:
print(lst1)
lst1.pop()

['hari', 23, 9.1, 'true', 'hyderabad', 'hyderabad']


'hyderabad'

In [28]:
print(lst1)

['hari', 23, 9.1, 'true', 'hyderabad']


In [40]:

student_cgpa=float(input('enter cgpa : '))
if student_cgpa >= 3.8 :
    grade='A'

elif student_cgpa <= 3.8 :
    grade='B'

elif student_cgpa <=3 :
    grade='C'

else:
    grade='D'

print(f'student letter grade is {grade}')

enter cgpa :  5.8


student letter grade is A


In [43]:
list=['kabadi','ko kho','volleyball','cricket','tennis']
print(list[1:])
print(list[:1])
print(list[:3])
print(list[2:4])
print(list[-1])
print(list[-3])
print(list[1:-1])

['ko kho', 'volleyball', 'cricket', 'tennis']
['kabadi']
['kabadi', 'ko kho', 'volleyball']
['volleyball', 'cricket']
tennis
volleyball
['ko kho', 'volleyball', 'cricket']


PYTHON FOR DATA ANALYTICS YT COURSE

In [45]:
#list store multiple values start from index 0 to ...
lst=['abc']
print(lst)

['abc']


In [50]:
lst.append(25)
print(lst)
lst.remove(23)
print(lst)

['abc', 23, 23, 25, 25]
['abc', 23, 25, 25]


In [52]:
#tuple : store values but immutable () cant modified
t1=(23,4,5,3)
print(t1)

(23, 4, 5, 3)


In [ ]:
t1.append(27) 
print(t1) # cant add 

In [56]:
d1={"name":"hari","age":20,"weiht":45,"height":4.8,"location":"hyderabad"}
print(d1)

{'name': 'hari', 'age': 20, 'weiht': 45, 'height': 4.8, 'location': 'hyderabad'}


In [57]:
type(d1)

dict

In [ ]:
d1['name']

In [67]:
d1['name']='shiva'
print(d1)

{'name': 'shiva', 'age': 20, 'weiht': 45, 'height': 4.8, 'location': 'hyderabad'}


In [ ]:
sum=1+2+3+4+5
print(sum)

In [69]:
sum=0
for i in range(1, 10):
   sum+=i
    
print(sum)

45


In [71]:
sum=0
i=0
while(i<=10):
   sum+=i
   i+=1
print(sum)

55


In [73]:
def add(a,b):
    return a+b

In [74]:
add(10,20)

30

In [87]:
def sub(a,b):
    return a-b

def mul(a,b):
    return a*b
    
def div(a,b):
    return a/b

def pow(a,b):
    return a**b
    
print(sub(50,20))
print(mul(50,20))
print( div(50,20))
pow(50,20)

30
1000
2.5


9536743164062500000000000000000000

**NUMPY** ============== **PYTHON LIST**
- Speed========slow
- memory (more memory efficient) ========less efficient
- direct(vectorization)===========manual loop
- many powerful tools==========limited
- same data type only ========= mixed allowed
- fast ============ slow

**NP FUNCTIONS**
- np.arange
- np.linspace
- np.logspace
- np.zeros
- np.ones
- np.full
- np.empty
- np.random.rand
- np.random.randn

In [89]:
import numpy as np
import time

In [90]:
a=[1,2,3,4,5,6,7,8,9,10]*100000
start= time.time()
for i in range(len(a)):
    a[i]=a[i]*2
print(time.time()-start)

0.5028481483459473


In [92]:
a=[1,2,3,4,5,6,7,8,9,10]*100000
b=np.array(a)
start= time.time()
newb=b*2
print(time.time()-start)

0.001998424530029297


In [93]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [94]:
import numpy as np # alias -> np
np.array([2,3,4])

array([2, 3, 4])

In [97]:
arr=np.array([2,3,4])
arr.ndim

1

In [104]:
arr=np.array([[[]]])
arr.ndim
arr.shape

(1, 1, 0)

In [110]:
# lst=[0,1,,2,3,4,5,6,7,8,9,10]
# or loop also
# but we can write in nparray easily
import numpy as np # alias -> np
a=np.arange(0,10,2) #arange keyword used to et automatic value in  order ( start,stop,step)
print(a) 

[0 2 4 6 8]


In [111]:
arr=np.linspace(0,1,5) # start, stop, no of values
arr


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [113]:
arr=np.logspace(1,3,2)#loaritmic scale array (start,endin,power)
arr

array([  10., 1000.])

In [118]:
arr=np.zeros(10)
arr=np.zeros([3,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [120]:
arr=np.ones([3,3],dtype=int)
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [121]:
arr=np.full(10,2)
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [124]:
arr=np.full([5,2],8)
arr # [row,col],default value

array([[8, 8],
       [8, 8],
       [8, 8],
       [8, 8],
       [8, 8]])

In [126]:
arr=np.empty([2,3])
arr #uninitialized array -> create 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [129]:
arr=np.random.rand(3,3) # col,rows
arr

array([[0.57031489, 0.92077896, 0.89073945],
       [0.74381319, 0.87633863, 0.41610016],
       [0.30936204, 0.13269039, 0.52606198]])

In [130]:
arr=np.random.randn(3,3) # col,rows # random floats from standard normal distribution
arr

array([[ 0.21186492,  1.29102575,  0.23142871],
       [ 0.3036189 , -0.57040495,  0.54224912],
       [ 1.87237411,  0.16607711, -0.24956577]])

In [134]:
arr=np.random.randint(10,100,3) # statrt,stop,no of dimensions
arr

array([22, 84, 48])

NUMPY DATATYPES AND TYPE CASTING


In [136]:
a=np.array([1,2,3.2,4,5])
a

array([1. , 2. , 3.2, 4. , 5. ])

In [138]:
print(type(a))

<class 'numpy.ndarray'>


In [139]:
lst=['hari',32,'kabbadi',23]
a=np.array(lst)
a

array(['hari', '32', 'kabbadi', '23'], dtype='<U11')

In [142]:
arr=np.array([1,2,3.8,4], dtype=np.int64)
arr.dtype

dtype('int64')

TYPECASTING -- converting one data type to another

In [143]:
a=np.array([1,2,3])
arr.dtype

dtype('int64')

In [144]:
new =a.astype(np.float64)
new

array([1., 2., 3.])

In [146]:
new =a.astype(np.int64)
new

array([1, 2, 3], dtype=int64)

In [149]:
arr =np.array([[1,2,3],[4,5,6]])
arr.ndim

2

In [150]:
arr.shape

(2, 3)

In [151]:
arr.size

6

In [152]:
arr.itemsize

4

In [153]:
arr.dtype

dtype('int32')

ARRAY RESHAPING ---> reshape,ravel,flatten

In [159]:
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(3,2)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [160]:
ravel=reshaped.ravel() # canes can reflect
ravel

array([1, 2, 3, 4, 5, 6])

In [162]:
flat=reshaped.flatten()
flat # returns a copy, canes cant reflect 

array([1, 2, 3, 4, 5, 6])

In [163]:
flat[0]

1

ARITHMETIC OPERATION ON ARRAYS

In [164]:
a= np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [165]:
print(a-b)

[-3 -3 -3]


In [166]:
print(a*b)

[ 4 10 18]


In [167]:
print(a/b)

[0.25 0.4  0.5 ]


In [175]:
print(b//a)

[4 2 2]


In [174]:
print(b%a)

[0 1 0]


In [176]:
print(a**b)

[  1  32 729]


UNIVERAL FUNCTIONS

In [178]:
ar=np.array([1,4,9,16])
print(np.sqrt(ar))

[1. 2. 3. 4.]


In [179]:
#exponentional -> np.exp -> e^x -> x is an inteer
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [180]:
#sine function -> np.sin

an=np.array([0,np.pi,np.pi/2])
print(np.sin(an))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]


INDEXING AND SLICING

In [182]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
#indexing
print(a[2])
print(a[-1])
print(a[3])

3
10


In [194]:
#slicinggg
print(a[0:3])
print(a[5:9])
print(a[-0:-1])
print(a[0:9:2])
print(a[::2])

[1 2 3]
[6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[1 3 5 7 9]


In [195]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[0:2,0:3])

[[1 2 3]
 [4 5 6]]


In [196]:
print(matrix[1:,1:])

[[5 6]
 [8 9]]


In [197]:
#index arrays -> Advanced Indexing
#np.take -> built in function to perform indexin and slicing
a=np.array([1,2,3,4,5,6,7,8,9,10])
ind=[0,2]
print(np.take(arr,ind))

[1 3]


In [198]:
#iteratin wit nditer()
arr=np.array([[1,2],[3,4]])
for x in np.nditer(arr):
    print(x, end=" ")

1 2 3 4 

In [199]:
#ndenumerate() -> both index + value
for ind , x in np.ndenumerate(arr):
    print(ind,x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [200]:
#views vs copies
a=np.array([1,2,3,4,5])
view=arr[1:3]
view

array([[3, 4]])

In [201]:
view[0]=200
view

array([[200, 200]])

In [202]:
arr

array([[  1,   2],
       [200, 200]])

In [204]:
copy=arr[1:3].copy()
copy

array([[200, 200]])

In [208]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [209]:
print(a.transpose())


[[1 3]
 [2 4]]


In [212]:
#swapaxes ->swap 2 specific axes in a matrix
a=np.array([[[1,2],[3,4]]])
a.shape

(1, 2, 2)

In [214]:
swap=np.swapaxes(a,0,1)
swap.shape

(2, 1, 2)

In [222]:
#concatenation
a=np.array([[1,2],[5,6]])
b=np.array([[3,4],[7,8]])
com=np.concatenate((a,b)) #combines[]
com

array([[1, 2],
       [5, 6],
       [3, 4],
       [7, 8]])

In [223]:
com2=np.vstack((a,b))
com2 # combine values [[][]]

array([[1, 2],
       [5, 6],
       [3, 4],
       [7, 8]])

In [224]:
com3=np.hstack((a,b))
com3 # combine values [[][]]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [226]:
#splitin the array
print(np.split(a,2))

[array([[1, 2]]), array([[5, 6]])]


In [227]:
print(np.hsplit(a,2))

[array([[1],
       [5]]), array([[2],
       [6]])]


In [229]:
#repeatingg
arr=np.array([1,2,3])
print(np.repeat(arr,4))

[1 1 1 1 2 2 2 2 3 3 3 3]


In [230]:
#title - > repeat my wolearray
print(np.tile(arr,3))

[1 2 3 1 2 3 1 2 3]


In [233]:
#aggreaate functions
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))
print(np.std(arr))
print(np.max(arr))
print(np.min(arr))

6
2.0
2.0
0.6666666666666666
0.816496580927726
3
1


In [234]:
#cumulative opeations -> runningg total
arr

array([1, 2, 3])

In [235]:
print(np.cumsum(arr))

[1 3 6]


In [236]:
print(np.cumprod(arr))

[1 2 6]


CONDITIONAL BASED CHOICES

In [239]:
#WHERE
arr
result=np.where(arr<2,'low','high')
result

array(['low', 'high', 'high'], dtype='<U4')

In [242]:
#argwHERE : row-column positions for 2d arrays
arr
print(np.argwhere(arr>1))
      

[[1]
 [2]]


In [244]:
mask=np.logical_and(arr>15,arr<=35)
mask

array([False, False, False])

In [245]:
print(np.argwhere(matrix>5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [251]:
#logical and
arr=np.array([1,2,3,100,23,91])

In [252]:
mask=np.logical_and(arr>3,arr<6)
mask

array([False, False, False, False, False, False])

In [255]:
mask=np.logical_or(arr>3,arr<6)
mask
arr[mask]


array([  1,   2,   3, 100,  23,  91])

In [ ]:
#broadcastinggggg -- streatching small array to match the big one

RULES
1) if shapes are equal they're compatible
2) is one is 1. it can be stretced to match thhhe other
3) if shapeare diff and not 1 or equal-> error


In [256]:
img=np.array([[200,150],[100,250]])
img

array([[200, 150],
       [100, 250]])

In [257]:
bright=img+50
bright

array([[250, 200],
       [150, 300]])

In [ ]:
#vectorization - 
#np.vectorize() -> convert a regular function to be applied on an array

In [258]:
arr

array([  1,   2,   3, 100,  23,  91])

In [261]:
def square(x):
    return x*x

vfunc=np.vectorize(square)

    

In [262]:
print(vfunc(arr))

[    1     4     9 10000   529  8281]


In [263]:
#dealinggggg withh missinggggg values

#np.nan-> not a number

a=np.array([1,2,np.nan,4])
a

array([ 1.,  2., nan,  4.])

In [264]:
#np.inf and -no.inf->positiv and neative infinites
# np.isnan
# np.isinf
# np.isfinite

#-->tese ar ethhhe functions used todetect any null values, infinte vlues or finite values
print(np.isnan(a))

[False False  True False]


In [265]:
b=np.array([1,np.nan,10.2,40])
print(np.isinf(b))

[False False False False]


In [267]:
new=np.nan_to_num(b)
new

array([ 1. ,  0. , 10.2, 40. ])

===================================================**PANDAS**===================================================